import { Copy, MessageCircle, RefreshCw, Send } from "lucide-react";
import { useState } from "react";
import api from "../../api/client";
import { useToast } from "../../context/ToastContext";
import { statusText } from "../../utils/format";

export function ReminderPanel({ customer }) {
  const [language, setLanguage] = useState("hinglish");
  const [tone, setTone] = useState("polite");
  const [message, setMessage] = useState("");
  const [reminderId, setReminderId] = useState("");
  const [loading, setLoading] = useState(false);
  const { push } = useToast();

  async function generate() {
    setLoading(true);
    try {
      const response = await api.post("/ai/generate-reminder", {
        customerId: customer._id,
        language,
        tone
      });
      setMessage(response.data.message);
      setReminderId(response.data.reminder._id);
      push(`Reminder generated by ${response.data.generatedBy}`);
    } catch (error) {
      push(statusText(error), "error");
    } finally {
      setLoading(false);
    }
  }

  async function copy() {
    await navigator.clipboard.writeText(message);
    push("Reminder copied");
  }

  function openWhatsApp() {
    const phone = customer.phone ? customer.phone.replace(/\D/g, "") : "";
    const url = `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
    window.open(url, "_blank", "noopener,noreferrer");
  }

  async function markSent() {
    if (!reminderId) return;
    try {
      await api.put(`/ai/reminders/${reminderId}/sent`);
      push("Reminder marked as sent");
    } catch (error) {
      push(statusText(error), "error");
    }
  }

  return (
    <section className="panel">
      <h2 className="text-base font-semibold text-slate-950 dark:text-white">Payment reminder</h2>
      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        <label>
          <span className="label">Language</span>
          <select className="field" value={language} onChange={(event) => setLanguage(event.target.value)}>
            <option value="hinglish">Hinglish</option>
            <option value="hi">Hindi</option>
            <option value="en">English</option>
          </select>
        </label>
        <label>
          <span className="label">Tone</span>
          <select className="field" value={tone} onChange={(event) => setTone(event.target.value)}>
            <option value="polite">Polite</option>
            <option value="friendly">Friendly</option>
            <option value="professional">Professional</option>
            <option value="firm">Firm</option>
          </select>
        </label>
      </div>
      <button type="button" className="btn-primary mt-4" onClick={generate} disabled={loading}>
        <RefreshCw size={18} />
        {message ? "Regenerate" : "Generate"}
      </button>
      {message ? (
        <div className="mt-4">
          <label className="label" htmlFor="reminderMessage">
            Editable message
          </label>
          <textarea
            id="reminderMessage"
            className="field min-h-32"
            value={message}
            onChange={(event) => setMessage(event.target.value)}
          />
          <div className="mt-3 flex flex-wrap gap-2">
            <button type="button" className="btn-secondary" onClick={copy}>
              <Copy size={16} />
              Copy
            </button>
            <button type="button" className="btn-secondary" onClick={openWhatsApp} disabled={!message}>
              <MessageCircle size={16} />
              WhatsApp
            </button>
            <button type="button" className="btn-secondary" onClick={markSent} disabled={!reminderId}>
              <Send size={16} />
              Mark sent
            </button>
          </div>
        </div>
      ) : null}
    </section>
  );
}
